{"name": "test_VAAI", "status": "broken", "statusDetails": {"message": "pymysql.err.IntegrityError: (1062, \"Duplicate entry '10.226.49.138' for key 'trident_objs.PRIMARY'\")", "trace": "self = <test_VAAI.Test_Setup object at 0x7f32bf315d68>\nconfig = {'PowerStore': {'array': {'pwd': 'Password123!', 'url': '10.226.49.138', 'user': 'admin'}, 'esxi_hosts': ['10.226.69.132', '10.226.69.203', '10.226.69.204', '10.226.69.206'], 'log_extension': '.log', 'log_level': 'debug', ...}}\njsons = {'ip': {'ens192': {'gateway': '172.16.20.180', 'mask': '255.255.0.0', 'net': 'block-vaai', 'range': '172.16.98.200-172...tacenter': 'FileDatacenter', 'guestcredential': 'root:Admin@123', 'insecure': 'true', 'password': 'Password123!', ...}}\n\n    def test_VAAI(self,config,jsons):\n>       self.init(config,jsons)\n\ntestcase/PowerStore/Day0/VAAI/test_VAAI.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntestcase/PowerStore/Day0/VAAI/test_VAAI.py:36: in init\n    database.insert_data(sql)\ncommon/databases/database.py:61: in insert_data\n    cursor.execute(insert_sql)\n/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py:148: in execute\n    result = self._query(query)\n/usr/local/python3/lib/python3.7/site-packages/pymysql/cursors.py:310: in _query\n    conn.query(q)\n/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py:548: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py:775: in _read_query_result\n    result.read()\n/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py:1156: in read\n    first_packet = self.connection._read_packet()\n/usr/local/python3/lib/python3.7/site-packages/pymysql/connections.py:725: in _read_packet\n    packet.raise_for_error()\n/usr/local/python3/lib/python3.7/site-packages/pymysql/protocol.py:221: in raise_for_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndata = b\"\\xff&\\x04#23000Duplicate entry '10.226.49.138' for key 'trident_objs.PRIMARY'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack(\"<h\", data[1:3])[0]\n        errval = data[9:].decode(\"utf-8\", \"replace\")\n        errorclass = error_map.get(errno)\n        if errorclass is None:\n            errorclass = InternalError if errno < 1000 else OperationalError\n>       raise errorclass(errno, errval)\nE       pymysql.err.IntegrityError: (1062, \"Duplicate entry '10.226.49.138' for key 'trident_objs.PRIMARY'\")\n\n/usr/local/python3/lib/python3.7/site-packages/pymysql/err.py:143: IntegrityError"}, "start": 1678954529369, "stop": 1678954529402, "uuid": "0611c77d-b82c-4eb6-852d-e0f9278fea7e", "historyId": "977d32936728ac63f04bc1343eb33fc7", "testCaseId": "071f3cd834c21d0da8e84a8997be5834", "fullName": "testcase.PowerStore.Day0.VAAI.test_VAAI.Test_Setup#test_VAAI", "labels": [{"name": "parentSuite", "value": "testcase.PowerStore.Day0.VAAI"}, {"name": "suite", "value": "test_VAAI"}, {"name": "subSuite", "value": "Test_Setup"}, {"name": "host", "value": "localhost.localdomain"}, {"name": "thread", "value": "24469-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.PowerStore.Day0.VAAI.test_VAAI"}]}