{"name": "test_nfs_clean", "status": "broken", "statusDetails": {"message": "RuntimeError: Managed Object 10.226.68.206 not found.", "trace": "self = <test_VAAI.Test_Setup.Test_Clean object at 0x7f4fbc2f3470>\njsons = {'ip': {'ens192': {'gateway': '172.16.20.180', 'mask': '255.255.0.0', 'net': 'block-vaai', 'range': '172.16.98.200-172...tacenter': 'FileDatacenter', 'guestcredential': 'root:Admin@123', 'insecure': 'true', 'password': 'Password123!', ...}}\nconfig = {'PowerStore': {'array': {'pwd': 'Password123!', 'url': '10.226.49.138', 'user': 'admin'}, 'esxi_hosts': ['10.226.69.132', '10.226.69.203', '10.226.69.204', '10.226.68.206'], 'log_extension': '.log', 'log_level': 'debug', ...}}\n\n    def test_nfs_clean(self,jsons,config):\n        self.init_vcenter_info(jsons)\n        self.delete_vm(jsons)\n>       self.delete_ds(config)\n\ntestcase/PowerStore/Day0/VAAI/test_VAAI.py:176: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntestcase/PowerStore/Day0/VAAI/test_VAAI.py:165: in delete_ds\n    self.esxiExecutor.delete_nfs_datastore(host)\nutils/os/Esxi.py:195: in delete_nfs_datastore\n    out =  self.execute(host,nfs_datastores_cmd)\nutils/os/Esxi.py:43: in execute\n    host_system = pchelper.get_obj(self.content,[vim.HostSystem],host)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncontent = (vim.ServiceInstanceContent) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   rootFolde...nager = <unset>,\n   siteInfoManager = <unset>,\n   storageQueryManager = 'vim.StorageQueryManager:StorageQueryManager'\n}\nvim_type = [<class 'pyVmomi.VmomiSupport.vim.HostSystem'>], name = '10.226.68.206', folder = None, recurse = True\n\n    def get_obj(content, vim_type, name, folder=None, recurse=True):\n        \"\"\"\n        Retrieves the managed object for the name and type specified\n        Throws an exception if of not found.\n        Sample Usage:\n        get_obj(content, [vim.Datastore], \"Datastore Name\")\n        \"\"\"\n        obj = search_for_obj(content, vim_type, name, folder, recurse)\n        if not obj:\n>           raise RuntimeError(\"Managed Object \" + name + \" not found.\")\nE           RuntimeError: Managed Object 10.226.68.206 not found.\n\nutils/os/pchelper.py:143: RuntimeError"}, "start": 1678953953366, "stop": 1678953991235, "uuid": "de6281b2-1fa2-4833-b451-2194c9a26899", "historyId": "48bc36b723190f30154c880ad19fbf35", "testCaseId": "13a9a953c24f63a2913e80156c740d55", "fullName": "testcase.PowerStore.Day0.VAAI.test_VAAI.Test_Setup#test_nfs_clean", "labels": [{"name": "parentSuite", "value": "testcase.PowerStore.Day0.VAAI"}, {"name": "suite", "value": "test_VAAI"}, {"name": "subSuite", "value": "Test_Setup"}, {"name": "host", "value": "localhost.localdomain"}, {"name": "thread", "value": "23182-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.PowerStore.Day0.VAAI.test_VAAI"}]}